# Generated by Django 5.0.6 on 2026-06-05 13:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='flyer',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='flyer'),
        ),
    ]
