# Generated by Django 5.0.6 on 2026-06-08 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_flyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='entry_fee',
        ),
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(help_text='Maximum number of physical individual attendees the venue can hold', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='flyer',
            field=models.ImageField(blank=True, null=True, upload_to='event_flyers/'),
        ),
    ]
