# Generated by Django 5.0.6 on 2026-06-05 13:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='qr_code',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='qr_code'),
        ),
    ]
