# Generated by Django 5.0.6 on 2026-06-08 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_tickettype_ticket_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='seats_per_ticket',
            field=models.PositiveIntegerField(default=1, help_text='How many individual people this single ticket choice admits (e.g., 1 for Regular, 12 for Royal Table)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='tier',
            field=models.CharField(choices=[('regular', 'Regular'), ('silver', 'Silver'), ('gold', 'Gold'), ('diamond_table', 'Diamond Table'), ('elite_table', 'Elite Table'), ('prestige_table', 'Prestige Table'), ('legacy_table', 'Legacy Table'), ('royal_table', 'Royal Table'), ('custom', 'Custom Tier')], default='regular', max_length=50),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='capacity',
            field=models.PositiveIntegerField(help_text='Maximum number of purchase slots for this ticket type'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='name',
            field=models.CharField(blank=True, help_text='Leave blank to use the tier name default', max_length=100),
        ),
    ]
